//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameClient.FriendshipServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendDto", Namespace="http://schemas.datacontract.org/2004/07/GameServer.Contracts")]
    [System.SerializableAttribute()]
    public partial class FriendDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvatarPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvatarPath {
            get {
                return this.AvatarPathField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarPathField, value) != true)) {
                    this.AvatarPathField = value;
                    this.RaisePropertyChanged("AvatarPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOnline {
            get {
                return this.IsOnlineField;
            }
            set {
                if ((this.IsOnlineField.Equals(value) != true)) {
                    this.IsOnlineField = value;
                    this.RaisePropertyChanged("IsOnline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FriendshipServiceReference.IFriendshipService")]
    public interface IFriendshipService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/SendFriendRequest", ReplyAction="http://tempuri.org/IFriendshipService/SendFriendRequestResponse")]
        bool SendFriendRequest(string senderUsername, string receiverUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/SendFriendRequest", ReplyAction="http://tempuri.org/IFriendshipService/SendFriendRequestResponse")]
        System.Threading.Tasks.Task<bool> SendFriendRequestAsync(string senderUsername, string receiverUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/RespondToFriendRequest", ReplyAction="http://tempuri.org/IFriendshipService/RespondToFriendRequestResponse")]
        bool RespondToFriendRequest(string respondingUsername, string requesterUsername, bool isAccepted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/RespondToFriendRequest", ReplyAction="http://tempuri.org/IFriendshipService/RespondToFriendRequestResponse")]
        System.Threading.Tasks.Task<bool> RespondToFriendRequestAsync(string respondingUsername, string requesterUsername, bool isAccepted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/GetFriendList", ReplyAction="http://tempuri.org/IFriendshipService/GetFriendListResponse")]
        GameClient.FriendshipServiceReference.FriendDto[] GetFriendList(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/GetFriendList", ReplyAction="http://tempuri.org/IFriendshipService/GetFriendListResponse")]
        System.Threading.Tasks.Task<GameClient.FriendshipServiceReference.FriendDto[]> GetFriendListAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/GetPendingRequests", ReplyAction="http://tempuri.org/IFriendshipService/GetPendingRequestsResponse")]
        GameClient.FriendshipServiceReference.FriendDto[] GetPendingRequests(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/GetPendingRequests", ReplyAction="http://tempuri.org/IFriendshipService/GetPendingRequestsResponse")]
        System.Threading.Tasks.Task<GameClient.FriendshipServiceReference.FriendDto[]> GetPendingRequestsAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFriendshipServiceChannel : GameClient.FriendshipServiceReference.IFriendshipService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FriendshipServiceClient : System.ServiceModel.ClientBase<GameClient.FriendshipServiceReference.IFriendshipService>, GameClient.FriendshipServiceReference.IFriendshipService {
        
        public FriendshipServiceClient() {
        }
        
        public FriendshipServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FriendshipServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FriendshipServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FriendshipServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SendFriendRequest(string senderUsername, string receiverUsername) {
            return base.Channel.SendFriendRequest(senderUsername, receiverUsername);
        }
        
        public System.Threading.Tasks.Task<bool> SendFriendRequestAsync(string senderUsername, string receiverUsername) {
            return base.Channel.SendFriendRequestAsync(senderUsername, receiverUsername);
        }
        
        public bool RespondToFriendRequest(string respondingUsername, string requesterUsername, bool isAccepted) {
            return base.Channel.RespondToFriendRequest(respondingUsername, requesterUsername, isAccepted);
        }
        
        public System.Threading.Tasks.Task<bool> RespondToFriendRequestAsync(string respondingUsername, string requesterUsername, bool isAccepted) {
            return base.Channel.RespondToFriendRequestAsync(respondingUsername, requesterUsername, isAccepted);
        }
        
        public GameClient.FriendshipServiceReference.FriendDto[] GetFriendList(string username) {
            return base.Channel.GetFriendList(username);
        }
        
        public System.Threading.Tasks.Task<GameClient.FriendshipServiceReference.FriendDto[]> GetFriendListAsync(string username) {
            return base.Channel.GetFriendListAsync(username);
        }
        
        public GameClient.FriendshipServiceReference.FriendDto[] GetPendingRequests(string username) {
            return base.Channel.GetPendingRequests(username);
        }
        
        public System.Threading.Tasks.Task<GameClient.FriendshipServiceReference.FriendDto[]> GetPendingRequestsAsync(string username) {
            return base.Channel.GetPendingRequestsAsync(username);
        }
    }
}
