//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameClient.FriendshipServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendRequestResult", Namespace="http://schemas.datacontract.org/2004/07/GameServer.DTOs.Friendship")]
    public enum FriendRequestResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AlreadyFriends = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TargetNotFound = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GuestRestriction = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespondRequestDto", Namespace="http://schemas.datacontract.org/2004/07/GameServer.DTOs.Friendship")]
    [System.SerializableAttribute()]
    public partial class RespondRequestDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAcceptedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequesterUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RespondingUsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAccepted {
            get {
                return this.IsAcceptedField;
            }
            set {
                if ((this.IsAcceptedField.Equals(value) != true)) {
                    this.IsAcceptedField = value;
                    this.RaisePropertyChanged("IsAccepted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequesterUsername {
            get {
                return this.RequesterUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.RequesterUsernameField, value) != true)) {
                    this.RequesterUsernameField = value;
                    this.RaisePropertyChanged("RequesterUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RespondingUsername {
            get {
                return this.RespondingUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.RespondingUsernameField, value) != true)) {
                    this.RespondingUsernameField = value;
                    this.RaisePropertyChanged("RespondingUsername");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendDto", Namespace="http://schemas.datacontract.org/2004/07/GameServer.DTOs.Friendship")]
    [System.SerializableAttribute()]
    public partial class FriendDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvatarPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvatarPath {
            get {
                return this.AvatarPathField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarPathField, value) != true)) {
                    this.AvatarPathField = value;
                    this.RaisePropertyChanged("AvatarPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOnline {
            get {
                return this.IsOnlineField;
            }
            set {
                if ((this.IsOnlineField.Equals(value) != true)) {
                    this.IsOnlineField = value;
                    this.RaisePropertyChanged("IsOnline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameInvitationDto", Namespace="http://schemas.datacontract.org/2004/07/GameServer.DTOs.Friendship")]
    [System.SerializableAttribute()]
    public partial class GameInvitationDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LobbyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetUsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LobbyCode {
            get {
                return this.LobbyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LobbyCodeField, value) != true)) {
                    this.LobbyCodeField = value;
                    this.RaisePropertyChanged("LobbyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderUsername {
            get {
                return this.SenderUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderUsernameField, value) != true)) {
                    this.SenderUsernameField = value;
                    this.RaisePropertyChanged("SenderUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetUsername {
            get {
                return this.TargetUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetUsernameField, value) != true)) {
                    this.TargetUsernameField = value;
                    this.RaisePropertyChanged("TargetUsername");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FriendshipServiceReference.IFriendshipService", CallbackContract=typeof(GameClient.FriendshipServiceReference.IFriendshipServiceCallback))]
    public interface IFriendshipService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/Connect", ReplyAction="http://tempuri.org/IFriendshipService/ConnectResponse")]
        void Connect(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/Connect", ReplyAction="http://tempuri.org/IFriendshipService/ConnectResponse")]
        System.Threading.Tasks.Task ConnectAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/Disconnect", ReplyAction="http://tempuri.org/IFriendshipService/DisconnectResponse")]
        void Disconnect(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/Disconnect", ReplyAction="http://tempuri.org/IFriendshipService/DisconnectResponse")]
        System.Threading.Tasks.Task DisconnectAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/SendFriendRequest", ReplyAction="http://tempuri.org/IFriendshipService/SendFriendRequestResponse")]
        GameClient.FriendshipServiceReference.FriendRequestResult SendFriendRequest(string senderUsername, string receiverUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/SendFriendRequest", ReplyAction="http://tempuri.org/IFriendshipService/SendFriendRequestResponse")]
        System.Threading.Tasks.Task<GameClient.FriendshipServiceReference.FriendRequestResult> SendFriendRequestAsync(string senderUsername, string receiverUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/RespondToFriendRequest", ReplyAction="http://tempuri.org/IFriendshipService/RespondToFriendRequestResponse")]
        bool RespondToFriendRequest(GameClient.FriendshipServiceReference.RespondRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/RespondToFriendRequest", ReplyAction="http://tempuri.org/IFriendshipService/RespondToFriendRequestResponse")]
        System.Threading.Tasks.Task<bool> RespondToFriendRequestAsync(GameClient.FriendshipServiceReference.RespondRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/GetFriendList", ReplyAction="http://tempuri.org/IFriendshipService/GetFriendListResponse")]
        GameClient.FriendshipServiceReference.FriendDto[] GetFriendList(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/GetFriendList", ReplyAction="http://tempuri.org/IFriendshipService/GetFriendListResponse")]
        System.Threading.Tasks.Task<GameClient.FriendshipServiceReference.FriendDto[]> GetFriendListAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/GetPendingRequests", ReplyAction="http://tempuri.org/IFriendshipService/GetPendingRequestsResponse")]
        GameClient.FriendshipServiceReference.FriendDto[] GetPendingRequests(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/GetPendingRequests", ReplyAction="http://tempuri.org/IFriendshipService/GetPendingRequestsResponse")]
        System.Threading.Tasks.Task<GameClient.FriendshipServiceReference.FriendDto[]> GetPendingRequestsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/RemoveFriend", ReplyAction="http://tempuri.org/IFriendshipService/RemoveFriendResponse")]
        bool RemoveFriend(string username, string friendUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/RemoveFriend", ReplyAction="http://tempuri.org/IFriendshipService/RemoveFriendResponse")]
        System.Threading.Tasks.Task<bool> RemoveFriendAsync(string username, string friendUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/SendGameInvitation", ReplyAction="http://tempuri.org/IFriendshipService/SendGameInvitationResponse")]
        void SendGameInvitation(GameClient.FriendshipServiceReference.GameInvitationDto invitation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendshipService/SendGameInvitation", ReplyAction="http://tempuri.org/IFriendshipService/SendGameInvitationResponse")]
        System.Threading.Tasks.Task SendGameInvitationAsync(GameClient.FriendshipServiceReference.GameInvitationDto invitation);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFriendshipServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFriendshipService/OnFriendRequestReceived")]
        void OnFriendRequestReceived();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFriendshipService/OnFriendListUpdated")]
        void OnFriendListUpdated();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFriendshipService/OnGameInvitationReceived")]
        void OnGameInvitationReceived(string hostUsername, string lobbyCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFriendshipService/OnFriendRequestPopUp")]
        void OnFriendRequestPopUp(string senderUsername);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFriendshipServiceChannel : GameClient.FriendshipServiceReference.IFriendshipService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FriendshipServiceClient : System.ServiceModel.DuplexClientBase<GameClient.FriendshipServiceReference.IFriendshipService>, GameClient.FriendshipServiceReference.IFriendshipService {
        
        public FriendshipServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public FriendshipServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public FriendshipServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public FriendshipServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public FriendshipServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Connect(string username) {
            base.Channel.Connect(username);
        }
        
        public System.Threading.Tasks.Task ConnectAsync(string username) {
            return base.Channel.ConnectAsync(username);
        }
        
        public void Disconnect(string username) {
            base.Channel.Disconnect(username);
        }
        
        public System.Threading.Tasks.Task DisconnectAsync(string username) {
            return base.Channel.DisconnectAsync(username);
        }
        
        public GameClient.FriendshipServiceReference.FriendRequestResult SendFriendRequest(string senderUsername, string receiverUsername) {
            return base.Channel.SendFriendRequest(senderUsername, receiverUsername);
        }
        
        public System.Threading.Tasks.Task<GameClient.FriendshipServiceReference.FriendRequestResult> SendFriendRequestAsync(string senderUsername, string receiverUsername) {
            return base.Channel.SendFriendRequestAsync(senderUsername, receiverUsername);
        }
        
        public bool RespondToFriendRequest(GameClient.FriendshipServiceReference.RespondRequestDto request) {
            return base.Channel.RespondToFriendRequest(request);
        }
        
        public System.Threading.Tasks.Task<bool> RespondToFriendRequestAsync(GameClient.FriendshipServiceReference.RespondRequestDto request) {
            return base.Channel.RespondToFriendRequestAsync(request);
        }
        
        public GameClient.FriendshipServiceReference.FriendDto[] GetFriendList(string username) {
            return base.Channel.GetFriendList(username);
        }
        
        public System.Threading.Tasks.Task<GameClient.FriendshipServiceReference.FriendDto[]> GetFriendListAsync(string username) {
            return base.Channel.GetFriendListAsync(username);
        }
        
        public GameClient.FriendshipServiceReference.FriendDto[] GetPendingRequests(string username) {
            return base.Channel.GetPendingRequests(username);
        }
        
        public System.Threading.Tasks.Task<GameClient.FriendshipServiceReference.FriendDto[]> GetPendingRequestsAsync(string username) {
            return base.Channel.GetPendingRequestsAsync(username);
        }
        
        public bool RemoveFriend(string username, string friendUsername) {
            return base.Channel.RemoveFriend(username, friendUsername);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveFriendAsync(string username, string friendUsername) {
            return base.Channel.RemoveFriendAsync(username, friendUsername);
        }
        
        public void SendGameInvitation(GameClient.FriendshipServiceReference.GameInvitationDto invitation) {
            base.Channel.SendGameInvitation(invitation);
        }
        
        public System.Threading.Tasks.Task SendGameInvitationAsync(GameClient.FriendshipServiceReference.GameInvitationDto invitation) {
            return base.Channel.SendGameInvitationAsync(invitation);
        }
    }
}
