//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameClient.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameClient.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string AcceptButton {
            get {
                return ResourceManager.GetString("AcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string AceptButton {
            get {
                return ResourceManager.GetString("AceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya tienes una cuenta? Click aqui.
        /// </summary>
        public static string AlreadyHaveAccountText {
            get {
                return ResourceManager.GetString("AlreadyHaveAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar como invitado.
        /// </summary>
        public static string AsGuestButton {
            get {
                return ResourceManager.GetString("AsGuestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de formato en la imagen de avatar..
        /// </summary>
        public static string AvatarFormatError {
            get {
                return ResourceManager.GetString("AvatarFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error cargando avatares: {0}.
        /// </summary>
        public static string AvatarLoadError {
            get {
                return ResourceManager.GetString("AvatarLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al leer el archivo de avatar..
        /// </summary>
        public static string AvatarReadError {
            get {
                return ResourceManager.GetString("AvatarReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Avatar actualizado!.
        /// </summary>
        public static string AvatarUpdatedMessage {
            get {
                return ResourceManager.GetString("AvatarUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al actualizar..
        /// </summary>
        public static string AvatarUpdateError {
            get {
                return ResourceManager.GetString("AvatarUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        public static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tablero.
        /// </summary>
        public static string BoardHeader {
            get {
                return ResourceManager.GetString("BoardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de tablero.
        /// </summary>
        public static string BoardTypeLabel {
            get {
                return ResourceManager.GetString("BoardTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tablero Normal.
        /// </summary>
        public static string BoardTypeNormal {
            get {
                return ResourceManager.GetString("BoardTypeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tablero especial.
        /// </summary>
        public static string BoardTypeSpecial {
            get {
                return ResourceManager.GetString("BoardTypeSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventana sin Bordes.
        /// </summary>
        public static string BorderlessMode {
            get {
                return ResourceManager.GetString("BorderlessMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 📷 Cambiar Foto.
        /// </summary>
        public static string ChangeAvatarButton {
            get {
                return ResourceManager.GetString("ChangeAvatarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar.
        /// </summary>
        public static string ChangeButton {
            get {
                return ResourceManager.GetString("ChangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Contraseña.
        /// </summary>
        public static string ChangePasswordButton {
            get {
                return ResourceManager.GetString("ChangePasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Te quedan {0} cambios de nombre..
        /// </summary>
        public static string ChangesLeftMessage {
            get {
                return ResourceManager.GetString("ChangesLeftMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Sistema]: ¡Bienvenido a la partida!.
        /// </summary>
        public static string ChatSystemWelcome {
            get {
                return ResourceManager.GetString("ChatSystemWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CHAT.
        /// </summary>
        public static string ChatTabHeader {
            get {
                return ResourceManager.GetString("ChatTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código copiado.
        /// </summary>
        public static string CodeCopiedMessage {
            get {
                return ResourceManager.GetString("CodeCopiedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CÓDIGO:.
        /// </summary>
        public static string CodeLabel {
            get {
                return ResourceManager.GetString("CodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monedas:.
        /// </summary>
        public static string CoinsLabel {
            get {
                return ResourceManager.GetString("CoinsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de comunicación con el servidor. Revisa tu conexión..
        /// </summary>
        public static string ComunicationLabel {
            get {
                return ResourceManager.GetString("ComunicationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ComunicationTile {
            get {
                return ResourceManager.GetString("ComunicationTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Configuración aplicada correctamente!.
        /// </summary>
        public static string ConfigSavedMessage {
            get {
                return ResourceManager.GetString("ConfigSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones.
        /// </summary>
        public static string ConfigSavedTitle {
            get {
                return ResourceManager.GetString("ConfigSavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        public static string ConfirmationTitle {
            get {
                return ResourceManager.GetString("ConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        public static string ConfirmButton {
            get {
                return ResourceManager.GetString("ConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que quieres salir?.
        /// </summary>
        public static string ConfirmExitLabel {
            get {
                return ResourceManager.GetString("ConfirmExitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        public static string ConfirmTitle {
            get {
                return ResourceManager.GetString("ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copiar Código.
        /// </summary>
        public static string CopyCodeToolTip {
            get {
                return ResourceManager.GetString("CopyCodeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear cuenta.
        /// </summary>
        public static string CreateAccountButton {
            get {
                return ResourceManager.GetString("CreateAccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear sala.
        /// </summary>
        public static string CreateLobbyButton {
            get {
                return ResourceManager.GetString("CreateLobbyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear partida.
        /// </summary>
        public static string CreateMatchButton {
            get {
                return ResourceManager.GetString("CreateMatchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear partida.
        /// </summary>
        public static string CreateMatchTitle {
            get {
                return ResourceManager.GetString("CreateMatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Eliminar a {0}?.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Amigo.
        /// </summary>
        public static string DeleteFriendToolTip {
            get {
                return ResourceManager.GetString("DeleteFriendToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electronico.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo ya está en uso.
        /// </summary>
        public static string EmailUsedLabel {
            get {
                return ResourceManager.GetString("EmailUsedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string EmailUsedTitle {
            get {
                return ResourceManager.GetString("EmailUsedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no puede estar vacia.
        /// </summary>
        public static string EmptyPasswordLabel {
            get {
                return ResourceManager.GetString("EmptyPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor escribe un nombre de usuario..
        /// </summary>
        public static string EmptyUsernameError {
            get {
                return ResourceManager.GetString("EmptyUsernameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario o correo no puede estar vacío.
        /// </summary>
        public static string EmptyUsernameLabel {
            get {
                return ResourceManager.GetString("EmptyUsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo conectar al servidor. Asegúrate de que el servidor esté en ejecución.
        /// </summary>
        public static string EndpointNotFoundLabel {
            get {
                return ResourceManager.GetString("EndpointNotFoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de Conexión.
        /// </summary>
        public static string EndpointNotFoundTitle {
            get {
                return ResourceManager.GetString("EndpointNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instrucciones:.
        /// </summary>
        public static string EnterRecoveryCodeInstruction {
            get {
                return ResourceManager.GetString("EnterRecoveryCodeInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hubo un error.
        /// </summary>
        public static string ErrorLabel {
            get {
                return ResourceManager.GetString("ErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de Red.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Olvidaste tu contraseña?.
        /// </summary>
        public static string ForgotPassLabel {
            get {
                return ResourceManager.GetString("ForgotPassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigo eliminado..
        /// </summary>
        public static string FriendDeletedSuccess {
            get {
                return ResourceManager.GetString("FriendDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de Amigos.
        /// </summary>
        public static string FriendshipTitle {
            get {
                return ResourceManager.GetString("FriendshipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pantalla Completa.
        /// </summary>
        public static string FullScreenMode {
            get {
                return ResourceManager.GetString("FullScreenMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma del Juego.
        /// </summary>
        public static string GameLanguageLabel {
            get {
                return ResourceManager.GetString("GameLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partidas Jugadas:.
        /// </summary>
        public static string GamesPlayedLabel {
            get {
                return ResourceManager.GetString("GamesPlayedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Victorias:.
        /// </summary>
        public static string GamesWonLabel {
            get {
                return ResourceManager.GetString("GamesWonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Genial!.
        /// </summary>
        public static string GreatButton {
            get {
                return ResourceManager.GetString("GreatButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anfitrión.
        /// </summary>
        public static string HostHeader {
            get {
                return ResourceManager.GetString("HostHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Host).
        /// </summary>
        public static string HostLabel {
            get {
                return ResourceManager.GetString("HostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        public static string InfoTitle {
            get {
                return ResourceManager.GetString("InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, ingresa un código válido de 5 letras..
        /// </summary>
        public static string InvalidCodeMessage {
            get {
                return ResourceManager.GetString("InvalidCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código Inválido.
        /// </summary>
        public static string InvalidCodeTitle {
            get {
                return ResourceManager.GetString("InvalidCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviado.
        /// </summary>
        public static string InvitationSentButton {
            get {
                return ResourceManager.GetString("InvitationSentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitación enviada a {0}..
        /// </summary>
        public static string InvitationSentMessage {
            get {
                return ResourceManager.GetString("InvitationSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar.
        /// </summary>
        public static string InviteButton {
            get {
                return ResourceManager.GetString("InviteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar Amigos.
        /// </summary>
        public static string InviteFriendsTitle {
            get {
                return ResourceManager.GetString("InviteFriendsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar Amigos.
        /// </summary>
        public static string InviteFriendsToolTip {
            get {
                return ResourceManager.GetString("InviteFriendsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse.
        /// </summary>
        public static string JoinButton {
            get {
                return ResourceManager.GetString("JoinButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a partida.
        /// </summary>
        public static string JoinMatchButton {
            get {
                return ResourceManager.GetString("JoinMatchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el Código de Partida.
        /// </summary>
        public static string JoinMatchCodeTitle {
            get {
                return ResourceManager.GetString("JoinMatchCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English (US).
        /// </summary>
        public static string LanguageEn {
            get {
                return ResourceManager.GetString("LanguageEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español (ES).
        /// </summary>
        public static string LanguageEs {
            get {
                return ResourceManager.GetString("LanguageEs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Français (FR).
        /// </summary>
        public static string LanguageFr {
            get {
                return ResourceManager.GetString("LanguageFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string LanguageHeader {
            get {
                return ResourceManager.GetString("LanguageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abandonar Partida.
        /// </summary>
        public static string LeaveGameTitle {
            get {
                return ResourceManager.GetString("LeaveGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si sales ahora, contarás como derrota. ¿Seguro?.
        /// </summary>
        public static string LeaveGameWarning {
            get {
                return ResourceManager.GetString("LeaveGameWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has alcanzado el límite de cambios de nombre (3/3)..
        /// </summary>
        public static string LimitReachedMessage {
            get {
                return ResourceManager.GetString("LimitReachedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando....
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Partida.
        /// </summary>
        public static string LobbyPageTitle {
            get {
                return ResourceManager.GetString("LobbyPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesion.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario, correo o contraseña incorrectos.
        /// </summary>
        public static string LoginErrorLabel {
            get {
                return ResourceManager.GetString("LoginErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio Sesion.
        /// </summary>
        public static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar perfil.
        /// </summary>
        public static string ModifyProfileTitle {
            get {
                return ResourceManager.GetString("ModifyProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Música.
        /// </summary>
        public static string MusicLabel {
            get {
                return ResourceManager.GetString("MusicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Amigos.
        /// </summary>
        public static string MyFriendsTab {
            get {
                return ResourceManager.GetString("MyFriendsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva contraseña.
        /// </summary>
        public static string NewPasswordLabel {
            get {
                return ResourceManager.GetString("NewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes amigos aún..
        /// </summary>
        public static string NoFriendsMessage {
            get {
                return ResourceManager.GetString("NoFriendsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay amigos conectados..
        /// </summary>
        public static string NoFriendsOnline {
            get {
                return ResourceManager.GetString("NoFriendsOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string NoLabel {
            get {
                return ResourceManager.GetString("NoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay partidas disponibles..
        /// </summary>
        public static string NoMatchesLabel {
            get {
                return ResourceManager.GetString("NoMatchesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes solicitudes pendientes..
        /// </summary>
        public static string NoRequestsMessage {
            get {
                return ResourceManager.GetString("NoRequestsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones.
        /// </summary>
        public static string OptionsButton {
            get {
                return ResourceManager.GetString("OptionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OPCIONES.
        /// </summary>
        public static string OptionsPageTitle {
            get {
                return ResourceManager.GetString("OptionsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar.
        /// </summary>
        public static string PlayButton {
            get {
                return ResourceManager.GetString("PlayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero de jugadores.
        /// </summary>
        public static string PlayerCountLabel {
            get {
                return ResourceManager.GetString("PlayerCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2-4.
        /// </summary>
        public static string PlayerCountRange {
            get {
                return ResourceManager.GetString("PlayerCountRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugadores.
        /// </summary>
        public static string PlayersHeader {
            get {
                return ResourceManager.GetString("PlayersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugadores.
        /// </summary>
        public static string PlayersTabHeader {
            get {
                return ResourceManager.GetString("PlayersTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo cargar el perfil del usuario..
        /// </summary>
        public static string ProfileLoadError {
            get {
                return ResourceManager.GetString("ProfileLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PARTIDAS PÚBLICAS.
        /// </summary>
        public static string PublicMatchesTitle {
            get {
                return ResourceManager.GetString("PublicMatchesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string QuitButton {
            get {
                return ResourceManager.GetString("QuitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        public static string RefreshButton {
            get {
                return ResourceManager.GetString("RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string RegisterButtonText {
            get {
                return ResourceManager.GetString("RegisterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string RegisterPageTitle {
            get {
                return ResourceManager.GetString("RegisterPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro casi completo. Revisa tu correo para obtener el código de verificación (Spam), Revisa tu Correo.
        /// </summary>
        public static string RegisterSuccesfulLabel {
            get {
                return ResourceManager.GetString("RegisterSuccesfulLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro casi exitoso.
        /// </summary>
        public static string RegisterSuccessfulTitle {
            get {
                return ResourceManager.GetString("RegisterSuccessfulTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazar.
        /// </summary>
        public static string RejectButton {
            get {
                return ResourceManager.GetString("RejectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repetir correo.
        /// </summary>
        public static string RepeatEmailLabel {
            get {
                return ResourceManager.GetString("RepeatEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repitir contraseña.
        /// </summary>
        public static string RepeatNewPasswordLabel {
            get {
                return ResourceManager.GetString("RepeatNewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repetir contraseña.
        /// </summary>
        public static string RepeatPasswordLabel {
            get {
                return ResourceManager.GetString("RepeatPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a te envió una solicitud de amistad..
        /// </summary>
        public static string RequestReceivedMessage {
            get {
                return ResourceManager.GetString("RequestReceivedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo enviar (Usuario no existe o ya son amigos)..
        /// </summary>
        public static string RequestSentError {
            get {
                return ResourceManager.GetString("RequestSentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud enviada a {0}..
        /// </summary>
        public static string RequestSentSuccess {
            get {
                return ResourceManager.GetString("RequestSentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitudes.
        /// </summary>
        public static string RequestsTab {
            get {
                return ResourceManager.GetString("RequestsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reenviar codigo.
        /// </summary>
        public static string ResendCodeButton {
            get {
                return ResourceManager.GetString("ResendCodeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restablece tu contraseña:.
        /// </summary>
        public static string ResetPasswordInstruction {
            get {
                return ResourceManager.GetString("ResetPasswordInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restablecer contraseña.
        /// </summary>
        public static string ResetPasswordTitle {
            get {
                return ResourceManager.GetString("ResetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El idioma ha sido cambiado.
        /// </summary>
        public static string RestartMessage {
            get {
                return ResourceManager.GetString("RestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Avatar.
        /// </summary>
        public static string SaveAvatarButton {
            get {
                return ResourceManager.GetString("SaveAvatarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Cambios.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modo de Pantalla.
        /// </summary>
        public static string ScreenModeLabel {
            get {
                return ResourceManager.GetString("ScreenModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar usuario....
        /// </summary>
        public static string SearchUserPlaceholder {
            get {
                return ResourceManager.GetString("SearchUserPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elige una imagen de la galería.
        /// </summary>
        public static string SelectAvatarSubtitle {
            get {
                return ResourceManager.GetString("SelectAvatarSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECCIONA TU AVATAR.
        /// </summary>
        public static string SelectAvatarTitle {
            get {
                return ResourceManager.GetString("SelectAvatarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor selecciona una partida de la lista..
        /// </summary>
        public static string SelectMatchWarning {
            get {
                return ResourceManager.GetString("SelectMatchWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes enviarte solicitud a ti mismo..
        /// </summary>
        public static string SelfRequestError {
            get {
                return ResourceManager.GetString("SelfRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string SendButton {
            get {
                return ResourceManager.GetString("SendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar Solicitud.
        /// </summary>
        public static string SendRequestButton {
            get {
                return ResourceManager.GetString("SendRequestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Efectos (SFX).
        /// </summary>
        public static string SfxLabel {
            get {
                return ResourceManager.GetString("SfxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Slot Vacío.
        /// </summary>
        public static string SlotEmptyLabel {
            get {
                return ResourceManager.GetString("SlotEmptyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sonido.
        /// </summary>
        public static string SoundHeader {
            get {
                return ResourceManager.GetString("SoundHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Partida.
        /// </summary>
        public static string StartGameButton {
            get {
                return ResourceManager.GetString("StartGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al iniciar.
        /// </summary>
        public static string StartGameError {
            get {
                return ResourceManager.GetString("StartGameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Partida.
        /// </summary>
        public static string StartMatchButton {
            get {
                return ResourceManager.GetString("StartMatchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ESTADÍSTICAS.
        /// </summary>
        public static string StatsTitle {
            get {
                return ResourceManager.GetString("StatsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exitoso.
        /// </summary>
        public static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La solicitud tardó demasiado en responder. Revisa tu conexión.
        /// </summary>
        public static string TimeoutLabel {
            get {
                return ResourceManager.GetString("TimeoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error inesperado: {0} .
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error inesperado: {0}.
        /// </summary>
        public static string UnexpectedErrorMessage {
            get {
                return ResourceManager.GetString("UnexpectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario:.
        /// </summary>
        public static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario ya está en uso..
        /// </summary>
        public static string UsernameUsedLabel {
            get {
                return ResourceManager.GetString("UsernameUsedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string UsernameUseTitle {
            get {
                return ResourceManager.GetString("UsernameUseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MI PERFIL.
        /// </summary>
        public static string UserProfilePageTitle {
            get {
                return ResourceManager.GetString("UserProfilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo.
        /// </summary>
        public static string VerificationCodeLabel {
            get {
                return ResourceManager.GetString("VerificationCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instrucciones.
        /// </summary>
        public static string VerifyAccountInstructions {
            get {
                return ResourceManager.GetString("VerifyAccountInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificar cuenta.
        /// </summary>
        public static string VerifyAccountLabel {
            get {
                return ResourceManager.GetString("VerifyAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificar.
        /// </summary>
        public static string VerifyButton {
            get {
                return ResourceManager.GetString("VerifyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperacion.
        /// </summary>
        public static string VerifyRecoveryCodeLabel {
            get {
                return ResourceManager.GetString("VerifyRecoveryCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Video.
        /// </summary>
        public static string VideoHeader {
            get {
                return ResourceManager.GetString("VideoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partidas existentes.
        /// </summary>
        public static string ViewMatchesButton {
            get {
                return ResourceManager.GetString("ViewMatchesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibilidad.
        /// </summary>
        public static string VisibilityLabel {
            get {
                return ResourceManager.GetString("VisibilityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Privada.
        /// </summary>
        public static string VisibilityPrivate {
            get {
                return ResourceManager.GetString("VisibilityPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Publica.
        /// </summary>
        public static string VisibilityPublic {
            get {
                return ResourceManager.GetString("VisibilityPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esperando jugadores….
        /// </summary>
        public static string WaitingForPlayersLabel {
            get {
                return ResourceManager.GetString("WaitingForPlayersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aviso.
        /// </summary>
        public static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventana.
        /// </summary>
        public static string WindowedMode {
            get {
                return ResourceManager.GetString("WindowedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        public static string YesLabel {
            get {
                return ResourceManager.GetString("YesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Tú).
        /// </summary>
        public static string YouLabel {
            get {
                return ResourceManager.GetString("YouLabel", resourceCulture);
            }
        }
    }
}
