//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameClient.GameplayServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameplayRequest", Namespace="http://schemas.datacontract.org/2004/07/GameServer.DTOs.Gameplay")]
    [System.SerializableAttribute()]
    public partial class GameplayRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LobbyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LobbyCode {
            get {
                return this.LobbyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LobbyCodeField, value) != true)) {
                    this.LobbyCodeField = value;
                    this.RaisePropertyChanged("LobbyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DiceRollDto", Namespace="http://schemas.datacontract.org/2004/07/GameServer.DTOs.Gameplay")]
    [System.SerializableAttribute()]
    public partial class DiceRollDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiceOneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiceTwoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiceOne {
            get {
                return this.DiceOneField;
            }
            set {
                if ((this.DiceOneField.Equals(value) != true)) {
                    this.DiceOneField = value;
                    this.RaisePropertyChanged("DiceOne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiceTwo {
            get {
                return this.DiceTwoField;
            }
            set {
                if ((this.DiceTwoField.Equals(value) != true)) {
                    this.DiceTwoField = value;
                    this.RaisePropertyChanged("DiceTwo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameStateDto", Namespace="http://schemas.datacontract.org/2004/07/GameServer.DTOs.Gameplay")]
    [System.SerializableAttribute()]
    public partial class GameStateDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentTurnUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] GameLogField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsBannedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsGameOverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsKickedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMyTurnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LastDiceOneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LastDiceTwoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GameClient.GameplayServiceReference.PlayerPositionDto[] PlayerPositionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WinnerUsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentTurnUsername {
            get {
                return this.CurrentTurnUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentTurnUsernameField, value) != true)) {
                    this.CurrentTurnUsernameField = value;
                    this.RaisePropertyChanged("CurrentTurnUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] GameLog {
            get {
                return this.GameLogField;
            }
            set {
                if ((object.ReferenceEquals(this.GameLogField, value) != true)) {
                    this.GameLogField = value;
                    this.RaisePropertyChanged("GameLog");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBanned {
            get {
                return this.IsBannedField;
            }
            set {
                if ((this.IsBannedField.Equals(value) != true)) {
                    this.IsBannedField = value;
                    this.RaisePropertyChanged("IsBanned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsGameOver {
            get {
                return this.IsGameOverField;
            }
            set {
                if ((this.IsGameOverField.Equals(value) != true)) {
                    this.IsGameOverField = value;
                    this.RaisePropertyChanged("IsGameOver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsKicked {
            get {
                return this.IsKickedField;
            }
            set {
                if ((this.IsKickedField.Equals(value) != true)) {
                    this.IsKickedField = value;
                    this.RaisePropertyChanged("IsKicked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMyTurn {
            get {
                return this.IsMyTurnField;
            }
            set {
                if ((this.IsMyTurnField.Equals(value) != true)) {
                    this.IsMyTurnField = value;
                    this.RaisePropertyChanged("IsMyTurn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LastDiceOne {
            get {
                return this.LastDiceOneField;
            }
            set {
                if ((this.LastDiceOneField.Equals(value) != true)) {
                    this.LastDiceOneField = value;
                    this.RaisePropertyChanged("LastDiceOne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LastDiceTwo {
            get {
                return this.LastDiceTwoField;
            }
            set {
                if ((this.LastDiceTwoField.Equals(value) != true)) {
                    this.LastDiceTwoField = value;
                    this.RaisePropertyChanged("LastDiceTwo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GameClient.GameplayServiceReference.PlayerPositionDto[] PlayerPositions {
            get {
                return this.PlayerPositionsField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerPositionsField, value) != true)) {
                    this.PlayerPositionsField = value;
                    this.RaisePropertyChanged("PlayerPositions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WinnerUsername {
            get {
                return this.WinnerUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.WinnerUsernameField, value) != true)) {
                    this.WinnerUsernameField = value;
                    this.RaisePropertyChanged("WinnerUsername");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerPositionDto", Namespace="http://schemas.datacontract.org/2004/07/GameServer.DTOs.Gameplay")]
    [System.SerializableAttribute()]
    public partial class PlayerPositionDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvatarPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentTileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMyTurnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvatarPath {
            get {
                return this.AvatarPathField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarPathField, value) != true)) {
                    this.AvatarPathField = value;
                    this.RaisePropertyChanged("AvatarPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentTile {
            get {
                return this.CurrentTileField;
            }
            set {
                if ((this.CurrentTileField.Equals(value) != true)) {
                    this.CurrentTileField = value;
                    this.RaisePropertyChanged("CurrentTile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMyTurn {
            get {
                return this.IsMyTurnField;
            }
            set {
                if ((this.IsMyTurnField.Equals(value) != true)) {
                    this.IsMyTurnField = value;
                    this.RaisePropertyChanged("IsMyTurn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOnline {
            get {
                return this.IsOnlineField;
            }
            set {
                if ((this.IsOnlineField.Equals(value) != true)) {
                    this.IsOnlineField = value;
                    this.RaisePropertyChanged("IsOnline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VoteRequestDto", Namespace="http://schemas.datacontract.org/2004/07/GameServer.DTOs.Gameplay")]
    [System.SerializableAttribute()]
    public partial class VoteRequestDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetUsername {
            get {
                return this.TargetUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetUsernameField, value) != true)) {
                    this.TargetUsernameField = value;
                    this.RaisePropertyChanged("TargetUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VoteResponseDto", Namespace="http://schemas.datacontract.org/2004/07/GameServer.DTOs.Gameplay")]
    [System.SerializableAttribute()]
    public partial class VoteResponseDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AcceptKickField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AcceptKick {
            get {
                return this.AcceptKickField;
            }
            set {
                if ((this.AcceptKickField.Equals(value) != true)) {
                    this.AcceptKickField = value;
                    this.RaisePropertyChanged("AcceptKick");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GameplayServiceReference.IGameplayService", CallbackContract=typeof(GameClient.GameplayServiceReference.IGameplayServiceCallback))]
    public interface IGameplayService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameplayService/RollDice", ReplyAction="http://tempuri.org/IGameplayService/RollDiceResponse")]
        GameClient.GameplayServiceReference.DiceRollDto RollDice(GameClient.GameplayServiceReference.GameplayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameplayService/RollDice", ReplyAction="http://tempuri.org/IGameplayService/RollDiceResponse")]
        System.Threading.Tasks.Task<GameClient.GameplayServiceReference.DiceRollDto> RollDiceAsync(GameClient.GameplayServiceReference.GameplayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameplayService/GetGameState", ReplyAction="http://tempuri.org/IGameplayService/GetGameStateResponse")]
        GameClient.GameplayServiceReference.GameStateDto GetGameState(GameClient.GameplayServiceReference.GameplayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameplayService/GetGameState", ReplyAction="http://tempuri.org/IGameplayService/GetGameStateResponse")]
        System.Threading.Tasks.Task<GameClient.GameplayServiceReference.GameStateDto> GetGameStateAsync(GameClient.GameplayServiceReference.GameplayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameplayService/LeaveGame", ReplyAction="http://tempuri.org/IGameplayService/LeaveGameResponse")]
        bool LeaveGame(GameClient.GameplayServiceReference.GameplayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameplayService/LeaveGame", ReplyAction="http://tempuri.org/IGameplayService/LeaveGameResponse")]
        System.Threading.Tasks.Task<bool> LeaveGameAsync(GameClient.GameplayServiceReference.GameplayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameplayService/InitiateVoteKick", ReplyAction="http://tempuri.org/IGameplayService/InitiateVoteKickResponse")]
        void InitiateVoteKick(GameClient.GameplayServiceReference.VoteRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameplayService/InitiateVoteKick", ReplyAction="http://tempuri.org/IGameplayService/InitiateVoteKickResponse")]
        System.Threading.Tasks.Task InitiateVoteKickAsync(GameClient.GameplayServiceReference.VoteRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameplayService/CastVote", ReplyAction="http://tempuri.org/IGameplayService/CastVoteResponse")]
        void CastVote(GameClient.GameplayServiceReference.VoteResponseDto vote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameplayService/CastVote", ReplyAction="http://tempuri.org/IGameplayService/CastVoteResponse")]
        System.Threading.Tasks.Task CastVoteAsync(GameClient.GameplayServiceReference.VoteResponseDto vote);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameplayServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameplayService/OnVoteKickStarted")]
        void OnVoteKickStarted(string targetUsername, string reason);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameplayService/OnPlayerKicked")]
        void OnPlayerKicked(string reason);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameplayService/OnTurnChanged")]
        void OnTurnChanged(GameClient.GameplayServiceReference.GameStateDto newState);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameplayService/OnGameFinished")]
        void OnGameFinished(string winner);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameplayServiceChannel : GameClient.GameplayServiceReference.IGameplayService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameplayServiceClient : System.ServiceModel.DuplexClientBase<GameClient.GameplayServiceReference.IGameplayService>, GameClient.GameplayServiceReference.IGameplayService {
        
        public GameplayServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GameplayServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GameplayServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameplayServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameplayServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public GameClient.GameplayServiceReference.DiceRollDto RollDice(GameClient.GameplayServiceReference.GameplayRequest request) {
            return base.Channel.RollDice(request);
        }
        
        public System.Threading.Tasks.Task<GameClient.GameplayServiceReference.DiceRollDto> RollDiceAsync(GameClient.GameplayServiceReference.GameplayRequest request) {
            return base.Channel.RollDiceAsync(request);
        }
        
        public GameClient.GameplayServiceReference.GameStateDto GetGameState(GameClient.GameplayServiceReference.GameplayRequest request) {
            return base.Channel.GetGameState(request);
        }
        
        public System.Threading.Tasks.Task<GameClient.GameplayServiceReference.GameStateDto> GetGameStateAsync(GameClient.GameplayServiceReference.GameplayRequest request) {
            return base.Channel.GetGameStateAsync(request);
        }
        
        public bool LeaveGame(GameClient.GameplayServiceReference.GameplayRequest request) {
            return base.Channel.LeaveGame(request);
        }
        
        public System.Threading.Tasks.Task<bool> LeaveGameAsync(GameClient.GameplayServiceReference.GameplayRequest request) {
            return base.Channel.LeaveGameAsync(request);
        }
        
        public void InitiateVoteKick(GameClient.GameplayServiceReference.VoteRequestDto request) {
            base.Channel.InitiateVoteKick(request);
        }
        
        public System.Threading.Tasks.Task InitiateVoteKickAsync(GameClient.GameplayServiceReference.VoteRequestDto request) {
            return base.Channel.InitiateVoteKickAsync(request);
        }
        
        public void CastVote(GameClient.GameplayServiceReference.VoteResponseDto vote) {
            base.Channel.CastVote(vote);
        }
        
        public System.Threading.Tasks.Task CastVoteAsync(GameClient.GameplayServiceReference.VoteResponseDto vote) {
            return base.Channel.CastVoteAsync(vote);
        }
    }
}
