//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameClient.GameplayServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DiceRollDTO", Namespace="http://schemas.datacontract.org/2004/07/GameServer.Contracts")]
    [System.SerializableAttribute()]
    public partial class DiceRollDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiceOneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiceTwoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiceOne {
            get {
                return this.DiceOneField;
            }
            set {
                if ((this.DiceOneField.Equals(value) != true)) {
                    this.DiceOneField = value;
                    this.RaisePropertyChanged("DiceOne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiceTwo {
            get {
                return this.DiceTwoField;
            }
            set {
                if ((this.DiceTwoField.Equals(value) != true)) {
                    this.DiceTwoField = value;
                    this.RaisePropertyChanged("DiceTwo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameStateDTO", Namespace="http://schemas.datacontract.org/2004/07/GameServer.Contracts")]
    [System.SerializableAttribute()]
    public partial class GameStateDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentTurnUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] GameLogField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsGameOverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMyTurnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LastDiceOneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LastDiceTwoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GameClient.GameplayServiceReference.PlayerPositionDTO[] PlayerPositionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WinnerUsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentTurnUsername {
            get {
                return this.CurrentTurnUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentTurnUsernameField, value) != true)) {
                    this.CurrentTurnUsernameField = value;
                    this.RaisePropertyChanged("CurrentTurnUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] GameLog {
            get {
                return this.GameLogField;
            }
            set {
                if ((object.ReferenceEquals(this.GameLogField, value) != true)) {
                    this.GameLogField = value;
                    this.RaisePropertyChanged("GameLog");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsGameOver {
            get {
                return this.IsGameOverField;
            }
            set {
                if ((this.IsGameOverField.Equals(value) != true)) {
                    this.IsGameOverField = value;
                    this.RaisePropertyChanged("IsGameOver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMyTurn {
            get {
                return this.IsMyTurnField;
            }
            set {
                if ((this.IsMyTurnField.Equals(value) != true)) {
                    this.IsMyTurnField = value;
                    this.RaisePropertyChanged("IsMyTurn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LastDiceOne {
            get {
                return this.LastDiceOneField;
            }
            set {
                if ((this.LastDiceOneField.Equals(value) != true)) {
                    this.LastDiceOneField = value;
                    this.RaisePropertyChanged("LastDiceOne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LastDiceTwo {
            get {
                return this.LastDiceTwoField;
            }
            set {
                if ((this.LastDiceTwoField.Equals(value) != true)) {
                    this.LastDiceTwoField = value;
                    this.RaisePropertyChanged("LastDiceTwo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GameClient.GameplayServiceReference.PlayerPositionDTO[] PlayerPositions {
            get {
                return this.PlayerPositionsField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerPositionsField, value) != true)) {
                    this.PlayerPositionsField = value;
                    this.RaisePropertyChanged("PlayerPositions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WinnerUsername {
            get {
                return this.WinnerUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.WinnerUsernameField, value) != true)) {
                    this.WinnerUsernameField = value;
                    this.RaisePropertyChanged("WinnerUsername");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerPositionDTO", Namespace="http://schemas.datacontract.org/2004/07/GameServer.Contracts")]
    [System.SerializableAttribute()]
    public partial class PlayerPositionDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentTileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentTile {
            get {
                return this.CurrentTileField;
            }
            set {
                if ((this.CurrentTileField.Equals(value) != true)) {
                    this.CurrentTileField = value;
                    this.RaisePropertyChanged("CurrentTile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOnline {
            get {
                return this.IsOnlineField;
            }
            set {
                if ((this.IsOnlineField.Equals(value) != true)) {
                    this.IsOnlineField = value;
                    this.RaisePropertyChanged("IsOnline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GameplayServiceReference.IGameplayService")]
    public interface IGameplayService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameplayService/RollDice", ReplyAction="http://tempuri.org/IGameplayService/RollDiceResponse")]
        GameClient.GameplayServiceReference.DiceRollDTO RollDice(string lobbyCode, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameplayService/RollDice", ReplyAction="http://tempuri.org/IGameplayService/RollDiceResponse")]
        System.Threading.Tasks.Task<GameClient.GameplayServiceReference.DiceRollDTO> RollDiceAsync(string lobbyCode, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameplayService/GetGameState", ReplyAction="http://tempuri.org/IGameplayService/GetGameStateResponse")]
        GameClient.GameplayServiceReference.GameStateDTO GetGameState(string lobbyCode, string requestingUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameplayService/GetGameState", ReplyAction="http://tempuri.org/IGameplayService/GetGameStateResponse")]
        System.Threading.Tasks.Task<GameClient.GameplayServiceReference.GameStateDTO> GetGameStateAsync(string lobbyCode, string requestingUsername);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameplayServiceChannel : GameClient.GameplayServiceReference.IGameplayService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameplayServiceClient : System.ServiceModel.ClientBase<GameClient.GameplayServiceReference.IGameplayService>, GameClient.GameplayServiceReference.IGameplayService {
        
        public GameplayServiceClient() {
        }
        
        public GameplayServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameplayServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameplayServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameplayServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GameClient.GameplayServiceReference.DiceRollDTO RollDice(string lobbyCode, string username) {
            return base.Channel.RollDice(lobbyCode, username);
        }
        
        public System.Threading.Tasks.Task<GameClient.GameplayServiceReference.DiceRollDTO> RollDiceAsync(string lobbyCode, string username) {
            return base.Channel.RollDiceAsync(lobbyCode, username);
        }
        
        public GameClient.GameplayServiceReference.GameStateDTO GetGameState(string lobbyCode, string requestingUsername) {
            return base.Channel.GetGameState(lobbyCode, requestingUsername);
        }
        
        public System.Threading.Tasks.Task<GameClient.GameplayServiceReference.GameStateDTO> GetGameStateAsync(string lobbyCode, string requestingUsername) {
            return base.Channel.GetGameStateAsync(lobbyCode, requestingUsername);
        }
    }
}
