//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameClient.UserProfileServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserProfileDto", Namespace="http://schemas.datacontract.org/2004/07/GameServer.DTOs.User")]
    [System.SerializableAttribute()]
    public partial class UserProfileDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvatarPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CoinsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchesPlayedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchesWonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsernameChangeCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvatarPath {
            get {
                return this.AvatarPathField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarPathField, value) != true)) {
                    this.AvatarPathField = value;
                    this.RaisePropertyChanged("AvatarPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Coins {
            get {
                return this.CoinsField;
            }
            set {
                if ((this.CoinsField.Equals(value) != true)) {
                    this.CoinsField = value;
                    this.RaisePropertyChanged("Coins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchesPlayed {
            get {
                return this.MatchesPlayedField;
            }
            set {
                if ((this.MatchesPlayedField.Equals(value) != true)) {
                    this.MatchesPlayedField = value;
                    this.RaisePropertyChanged("MatchesPlayed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchesWon {
            get {
                return this.MatchesWonField;
            }
            set {
                if ((this.MatchesWonField.Equals(value) != true)) {
                    this.MatchesWonField = value;
                    this.RaisePropertyChanged("MatchesWon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsernameChangeCount {
            get {
                return this.UsernameChangeCountField;
            }
            set {
                if ((this.UsernameChangeCountField.Equals(value) != true)) {
                    this.UsernameChangeCountField = value;
                    this.RaisePropertyChanged("UsernameChangeCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsernameChangeResult", Namespace="http://schemas.datacontract.org/2004/07/GameServer.DTOs.User")]
    public enum UsernameChangeResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UsernameAlreadyExists = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LimitReached = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CooldownActive = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserNotFound = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FatalError = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IncorrectPassword = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangePasswordRequest", Namespace="http://schemas.datacontract.org/2004/07/GameServer.DTOs.User")]
    [System.SerializableAttribute()]
    public partial class ChangePasswordRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewPassword {
            get {
                return this.NewPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.NewPasswordField, value) != true)) {
                    this.NewPasswordField = value;
                    this.RaisePropertyChanged("NewPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeactivateAccountRequest", Namespace="http://schemas.datacontract.org/2004/07/GameServer.DTOs.User")]
    [System.SerializableAttribute()]
    public partial class DeactivateAccountRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserProfileServiceReference.IUserProfileService")]
    public interface IUserProfileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/GetUserProfile", ReplyAction="http://tempuri.org/IUserProfileService/GetUserProfileResponse")]
        GameClient.UserProfileServiceReference.UserProfileDto GetUserProfile(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/GetUserProfile", ReplyAction="http://tempuri.org/IUserProfileService/GetUserProfileResponse")]
        System.Threading.Tasks.Task<GameClient.UserProfileServiceReference.UserProfileDto> GetUserProfileAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/ChangeUsername", ReplyAction="http://tempuri.org/IUserProfileService/ChangeUsernameResponse")]
        GameClient.UserProfileServiceReference.UsernameChangeResult ChangeUsername(string email, string newUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/ChangeUsername", ReplyAction="http://tempuri.org/IUserProfileService/ChangeUsernameResponse")]
        System.Threading.Tasks.Task<GameClient.UserProfileServiceReference.UsernameChangeResult> ChangeUsernameAsync(string email, string newUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/ChangeAvatar", ReplyAction="http://tempuri.org/IUserProfileService/ChangeAvatarResponse")]
        bool ChangeAvatar(string email, string avatarName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/ChangeAvatar", ReplyAction="http://tempuri.org/IUserProfileService/ChangeAvatarResponse")]
        System.Threading.Tasks.Task<bool> ChangeAvatarAsync(string email, string avatarName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/SendPasswordChangeCode", ReplyAction="http://tempuri.org/IUserProfileService/SendPasswordChangeCodeResponse")]
        bool SendPasswordChangeCode(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/SendPasswordChangeCode", ReplyAction="http://tempuri.org/IUserProfileService/SendPasswordChangeCodeResponse")]
        System.Threading.Tasks.Task<bool> SendPasswordChangeCodeAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/ChangePasswordWithCode", ReplyAction="http://tempuri.org/IUserProfileService/ChangePasswordWithCodeResponse")]
        bool ChangePasswordWithCode(GameClient.UserProfileServiceReference.ChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/ChangePasswordWithCode", ReplyAction="http://tempuri.org/IUserProfileService/ChangePasswordWithCodeResponse")]
        System.Threading.Tasks.Task<bool> ChangePasswordWithCodeAsync(GameClient.UserProfileServiceReference.ChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/DeactivateAccount", ReplyAction="http://tempuri.org/IUserProfileService/DeactivateAccountResponse")]
        bool DeactivateAccount(GameClient.UserProfileServiceReference.DeactivateAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/DeactivateAccount", ReplyAction="http://tempuri.org/IUserProfileService/DeactivateAccountResponse")]
        System.Threading.Tasks.Task<bool> DeactivateAccountAsync(GameClient.UserProfileServiceReference.DeactivateAccountRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserProfileServiceChannel : GameClient.UserProfileServiceReference.IUserProfileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserProfileServiceClient : System.ServiceModel.ClientBase<GameClient.UserProfileServiceReference.IUserProfileService>, GameClient.UserProfileServiceReference.IUserProfileService {
        
        public UserProfileServiceClient() {
        }
        
        public UserProfileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserProfileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserProfileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserProfileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GameClient.UserProfileServiceReference.UserProfileDto GetUserProfile(string email) {
            return base.Channel.GetUserProfile(email);
        }
        
        public System.Threading.Tasks.Task<GameClient.UserProfileServiceReference.UserProfileDto> GetUserProfileAsync(string email) {
            return base.Channel.GetUserProfileAsync(email);
        }
        
        public GameClient.UserProfileServiceReference.UsernameChangeResult ChangeUsername(string email, string newUsername) {
            return base.Channel.ChangeUsername(email, newUsername);
        }
        
        public System.Threading.Tasks.Task<GameClient.UserProfileServiceReference.UsernameChangeResult> ChangeUsernameAsync(string email, string newUsername) {
            return base.Channel.ChangeUsernameAsync(email, newUsername);
        }
        
        public bool ChangeAvatar(string email, string avatarName) {
            return base.Channel.ChangeAvatar(email, avatarName);
        }
        
        public System.Threading.Tasks.Task<bool> ChangeAvatarAsync(string email, string avatarName) {
            return base.Channel.ChangeAvatarAsync(email, avatarName);
        }
        
        public bool SendPasswordChangeCode(string email) {
            return base.Channel.SendPasswordChangeCode(email);
        }
        
        public System.Threading.Tasks.Task<bool> SendPasswordChangeCodeAsync(string email) {
            return base.Channel.SendPasswordChangeCodeAsync(email);
        }
        
        public bool ChangePasswordWithCode(GameClient.UserProfileServiceReference.ChangePasswordRequest request) {
            return base.Channel.ChangePasswordWithCode(request);
        }
        
        public System.Threading.Tasks.Task<bool> ChangePasswordWithCodeAsync(GameClient.UserProfileServiceReference.ChangePasswordRequest request) {
            return base.Channel.ChangePasswordWithCodeAsync(request);
        }
        
        public bool DeactivateAccount(GameClient.UserProfileServiceReference.DeactivateAccountRequest request) {
            return base.Channel.DeactivateAccount(request);
        }
        
        public System.Threading.Tasks.Task<bool> DeactivateAccountAsync(GameClient.UserProfileServiceReference.DeactivateAccountRequest request) {
            return base.Channel.DeactivateAccountAsync(request);
        }
    }
}
