//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GameDatabaseContainer : DbContext
    {
        public GameDatabaseContainer()
            : base("name=GameDatabaseContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Board> BoardSet { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<PlayerStat> PlayerStats { get; set; }
        public virtual DbSet<Friendship> Friendships { get; set; }
        public virtual DbSet<Sanction> Sanctions { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<PlayerInventory> PlayerInventories { get; set; }
        public virtual DbSet<Tile> Tiles { get; set; }
        public virtual DbSet<ChatMessage> ChatMessages { get; set; }
        public virtual DbSet<MoveRecord> MoveRecords { get; set; }
    }
}
