//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int IdGame { get; set; }
        public GameStatus GameStatus { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string HostPlayerID { get; set; }
        public int ChatMessageIdChatMessage { get; set; }
    
        public virtual Board Board { get; set; }
        public virtual ChatMessage ChatMessage { get; set; }
    }
}
