//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.MaxPlayers = 4;
            this.IsPublic = true;
            this.MoveRecords = new HashSet<MoveRecord>();
            this.Sanctions = new HashSet<Sanction>();
        }
    
        public int IdGame { get; set; }
        public int GameStatus { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int HostPlayerID { get; set; }
        public Nullable<int> ChatMessageIdChatMessage { get; set; }
        public int Board_idBoard { get; set; }
        public string LobbyCode { get; set; }
        public int MaxPlayers { get; set; }
        public bool IsPublic { get; set; }
        public Nullable<int> WinnerIdPlayer { get; set; }
    
        public virtual BoardSet BoardSet { get; set; }
        public virtual ChatMessage ChatMessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoveRecord> MoveRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sanction> Sanctions { get; set; }
    }
}
