//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoveRecord
    {
        public int IdMoveRecord { get; set; }
        public int TurnNumber { get; set; }
        public int DiceOne { get; set; }
        public int DiceTwo { get; set; }
        public int StartPosition { get; set; }
        public int FinalPosition { get; set; }
        public string ActionDescription { get; set; }
        public int PlayerIdPlayer { get; set; }
        public int GameIdGame { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Game Game { get; set; }
    }
}
