//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int IdPlayer { get; set; }
        public string Username { get; set; }
        public int Coins { get; set; }
        public string Avatar { get; set; }
        public int PlayerInventoryIdPlayerInventory { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual PlayerInventory PlayerInventory { get; set; }
        public virtual ChatMessage ChatMessage { get; set; }
    }
}
