//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameClient.GameServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GameServiceReference.IGameService")]
    public interface IGameService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/RegistrarUsuario", ReplyAction="http://tempuri.org/IGameService/RegistrarUsuarioResponse")]
        bool RegistrarUsuario(string username, string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/RegistrarUsuario", ReplyAction="http://tempuri.org/IGameService/RegistrarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> RegistrarUsuarioAsync(string username, string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/IniciarSesion", ReplyAction="http://tempuri.org/IGameService/IniciarSesionResponse")]
        bool IniciarSesion(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/IniciarSesion", ReplyAction="http://tempuri.org/IGameService/IniciarSesionResponse")]
        System.Threading.Tasks.Task<bool> IniciarSesionAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameServiceChannel : GameClient.GameServiceReference.IGameService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameServiceClient : System.ServiceModel.ClientBase<GameClient.GameServiceReference.IGameService>, GameClient.GameServiceReference.IGameService {
        
        public GameServiceClient() {
        }
        
        public GameServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegistrarUsuario(string username, string email, string password) {
            return base.Channel.RegistrarUsuario(username, email, password);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarUsuarioAsync(string username, string email, string password) {
            return base.Channel.RegistrarUsuarioAsync(username, email, password);
        }
        
        public bool IniciarSesion(string username, string password) {
            return base.Channel.IniciarSesion(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> IniciarSesionAsync(string username, string password) {
            return base.Channel.IniciarSesionAsync(username, password);
        }
    }
}
