//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameClient.GameServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterUserRequest", Namespace="http://schemas.datacontract.org/2004/07/GameServer.DTOs.Auth")]
    [System.SerializableAttribute()]
    public partial class RegisterUserRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistrationResult", Namespace="http://schemas.datacontract.org/2004/07/GameServer.DTOs.Auth")]
    public enum RegistrationResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UsernameAlreadyExists = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmailAlreadyExists = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmailPendingVerification = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FatalError = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GameServiceReference.IGameService")]
    public interface IGameService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/RegisterUser", ReplyAction="http://tempuri.org/IGameService/RegisterUserResponse")]
        GameClient.GameServiceReference.RegistrationResult RegisterUser(GameClient.GameServiceReference.RegisterUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/RegisterUser", ReplyAction="http://tempuri.org/IGameService/RegisterUserResponse")]
        System.Threading.Tasks.Task<GameClient.GameServiceReference.RegistrationResult> RegisterUserAsync(GameClient.GameServiceReference.RegisterUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/LogIn", ReplyAction="http://tempuri.org/IGameService/LogInResponse")]
        bool LogIn(string usernameOrEmail, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/LogIn", ReplyAction="http://tempuri.org/IGameService/LogInResponse")]
        System.Threading.Tasks.Task<bool> LogInAsync(string usernameOrEmail, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/Logout", ReplyAction="http://tempuri.org/IGameService/LogoutResponse")]
        void Logout(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/Logout", ReplyAction="http://tempuri.org/IGameService/LogoutResponse")]
        System.Threading.Tasks.Task LogoutAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/VerifyAccount", ReplyAction="http://tempuri.org/IGameService/VerifyAccountResponse")]
        bool VerifyAccount(string email, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/VerifyAccount", ReplyAction="http://tempuri.org/IGameService/VerifyAccountResponse")]
        System.Threading.Tasks.Task<bool> VerifyAccountAsync(string email, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/RequestPasswordReset", ReplyAction="http://tempuri.org/IGameService/RequestPasswordResetResponse")]
        bool RequestPasswordReset(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/RequestPasswordReset", ReplyAction="http://tempuri.org/IGameService/RequestPasswordResetResponse")]
        System.Threading.Tasks.Task<bool> RequestPasswordResetAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/VerifyRecoveryCode", ReplyAction="http://tempuri.org/IGameService/VerifyRecoveryCodeResponse")]
        bool VerifyRecoveryCode(string email, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/VerifyRecoveryCode", ReplyAction="http://tempuri.org/IGameService/VerifyRecoveryCodeResponse")]
        System.Threading.Tasks.Task<bool> VerifyRecoveryCodeAsync(string email, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/UpdatePassword", ReplyAction="http://tempuri.org/IGameService/UpdatePasswordResponse")]
        bool UpdatePassword(string email, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/UpdatePassword", ReplyAction="http://tempuri.org/IGameService/UpdatePasswordResponse")]
        System.Threading.Tasks.Task<bool> UpdatePasswordAsync(string email, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/ResendVerificationCode", ReplyAction="http://tempuri.org/IGameService/ResendVerificationCodeResponse")]
        bool ResendVerificationCode(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/ResendVerificationCode", ReplyAction="http://tempuri.org/IGameService/ResendVerificationCodeResponse")]
        System.Threading.Tasks.Task<bool> ResendVerificationCodeAsync(string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameServiceChannel : GameClient.GameServiceReference.IGameService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameServiceClient : System.ServiceModel.ClientBase<GameClient.GameServiceReference.IGameService>, GameClient.GameServiceReference.IGameService {
        
        public GameServiceClient() {
        }
        
        public GameServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GameClient.GameServiceReference.RegistrationResult RegisterUser(GameClient.GameServiceReference.RegisterUserRequest request) {
            return base.Channel.RegisterUser(request);
        }
        
        public System.Threading.Tasks.Task<GameClient.GameServiceReference.RegistrationResult> RegisterUserAsync(GameClient.GameServiceReference.RegisterUserRequest request) {
            return base.Channel.RegisterUserAsync(request);
        }
        
        public bool LogIn(string usernameOrEmail, string password) {
            return base.Channel.LogIn(usernameOrEmail, password);
        }
        
        public System.Threading.Tasks.Task<bool> LogInAsync(string usernameOrEmail, string password) {
            return base.Channel.LogInAsync(usernameOrEmail, password);
        }
        
        public void Logout(string username) {
            base.Channel.Logout(username);
        }
        
        public System.Threading.Tasks.Task LogoutAsync(string username) {
            return base.Channel.LogoutAsync(username);
        }
        
        public bool VerifyAccount(string email, string code) {
            return base.Channel.VerifyAccount(email, code);
        }
        
        public System.Threading.Tasks.Task<bool> VerifyAccountAsync(string email, string code) {
            return base.Channel.VerifyAccountAsync(email, code);
        }
        
        public bool RequestPasswordReset(string email) {
            return base.Channel.RequestPasswordReset(email);
        }
        
        public System.Threading.Tasks.Task<bool> RequestPasswordResetAsync(string email) {
            return base.Channel.RequestPasswordResetAsync(email);
        }
        
        public bool VerifyRecoveryCode(string email, string code) {
            return base.Channel.VerifyRecoveryCode(email, code);
        }
        
        public System.Threading.Tasks.Task<bool> VerifyRecoveryCodeAsync(string email, string code) {
            return base.Channel.VerifyRecoveryCodeAsync(email, code);
        }
        
        public bool UpdatePassword(string email, string newPassword) {
            return base.Channel.UpdatePassword(email, newPassword);
        }
        
        public System.Threading.Tasks.Task<bool> UpdatePasswordAsync(string email, string newPassword) {
            return base.Channel.UpdatePasswordAsync(email, newPassword);
        }
        
        public bool ResendVerificationCode(string email) {
            return base.Channel.ResendVerificationCode(email);
        }
        
        public System.Threading.Tasks.Task<bool> ResendVerificationCodeAsync(string email) {
            return base.Channel.ResendVerificationCodeAsync(email);
        }
    }
}
