//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameClient.LeaderboardServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LeaderboardDto", Namespace="http://schemas.datacontract.org/2004/07/GameServer.DTOs")]
    [System.SerializableAttribute()]
    public partial class LeaderboardDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvatarPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCurrentUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WinsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvatarPath {
            get {
                return this.AvatarPathField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarPathField, value) != true)) {
                    this.AvatarPathField = value;
                    this.RaisePropertyChanged("AvatarPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCurrentUser {
            get {
                return this.IsCurrentUserField;
            }
            set {
                if ((this.IsCurrentUserField.Equals(value) != true)) {
                    this.IsCurrentUserField = value;
                    this.RaisePropertyChanged("IsCurrentUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rank {
            get {
                return this.RankField;
            }
            set {
                if ((this.RankField.Equals(value) != true)) {
                    this.RankField = value;
                    this.RaisePropertyChanged("Rank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Wins {
            get {
                return this.WinsField;
            }
            set {
                if ((this.WinsField.Equals(value) != true)) {
                    this.WinsField = value;
                    this.RaisePropertyChanged("Wins");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LeaderboardServiceReference.ILeaderboardService")]
    public interface ILeaderboardService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeaderboardService/GetGlobalLeaderboard", ReplyAction="http://tempuri.org/ILeaderboardService/GetGlobalLeaderboardResponse")]
        GameClient.LeaderboardServiceReference.LeaderboardDto[] GetGlobalLeaderboard(string requestingUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeaderboardService/GetGlobalLeaderboard", ReplyAction="http://tempuri.org/ILeaderboardService/GetGlobalLeaderboardResponse")]
        System.Threading.Tasks.Task<GameClient.LeaderboardServiceReference.LeaderboardDto[]> GetGlobalLeaderboardAsync(string requestingUsername);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILeaderboardServiceChannel : GameClient.LeaderboardServiceReference.ILeaderboardService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LeaderboardServiceClient : System.ServiceModel.ClientBase<GameClient.LeaderboardServiceReference.ILeaderboardService>, GameClient.LeaderboardServiceReference.ILeaderboardService {
        
        public LeaderboardServiceClient() {
        }
        
        public LeaderboardServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LeaderboardServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeaderboardServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeaderboardServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GameClient.LeaderboardServiceReference.LeaderboardDto[] GetGlobalLeaderboard(string requestingUsername) {
            return base.Channel.GetGlobalLeaderboard(requestingUsername);
        }
        
        public System.Threading.Tasks.Task<GameClient.LeaderboardServiceReference.LeaderboardDto[]> GetGlobalLeaderboardAsync(string requestingUsername) {
            return base.Channel.GetGlobalLeaderboardAsync(requestingUsername);
        }
    }
}
