//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameClient.ChatServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JoinChatRequest", Namespace="http://schemas.datacontract.org/2004/07/GameServer.DTOs.Chat")]
    [System.SerializableAttribute()]
    public partial class JoinChatRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LobbyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LobbyCode {
            get {
                return this.LobbyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LobbyCodeField, value) != true)) {
                    this.LobbyCodeField = value;
                    this.RaisePropertyChanged("LobbyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatOperationResult", Namespace="http://schemas.datacontract.org/2004/07/GameServer.DTOs.Chat")]
    public enum ChatOperationResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SpamBlocked = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContentBlocked = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TargetNotFound = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyNotFound = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MessageTooLong = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalError = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeneralError = 7,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatMessageDto", Namespace="http://schemas.datacontract.org/2004/07/GameServer.DTOs.Chat")]
    [System.SerializableAttribute()]
    public partial class ChatMessageDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPrivateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LobbyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimestampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPrivate {
            get {
                return this.IsPrivateField;
            }
            set {
                if ((this.IsPrivateField.Equals(value) != true)) {
                    this.IsPrivateField = value;
                    this.RaisePropertyChanged("IsPrivate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LobbyCode {
            get {
                return this.LobbyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LobbyCodeField, value) != true)) {
                    this.LobbyCodeField = value;
                    this.RaisePropertyChanged("LobbyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetUser {
            get {
                return this.TargetUserField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetUserField, value) != true)) {
                    this.TargetUserField = value;
                    this.RaisePropertyChanged("TargetUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChatServiceReference.IChatService", CallbackContract=typeof(GameClient.ChatServiceReference.IChatServiceCallback))]
    public interface IChatService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/JoinLobbyChat", ReplyAction="http://tempuri.org/IChatService/JoinLobbyChatResponse")]
        GameClient.ChatServiceReference.ChatOperationResult JoinLobbyChat(GameClient.ChatServiceReference.JoinChatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/JoinLobbyChat", ReplyAction="http://tempuri.org/IChatService/JoinLobbyChatResponse")]
        System.Threading.Tasks.Task<GameClient.ChatServiceReference.ChatOperationResult> JoinLobbyChatAsync(GameClient.ChatServiceReference.JoinChatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/SendLobbyMessage", ReplyAction="http://tempuri.org/IChatService/SendLobbyMessageResponse")]
        GameClient.ChatServiceReference.ChatOperationResult SendLobbyMessage(GameClient.ChatServiceReference.ChatMessageDto messageDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/SendLobbyMessage", ReplyAction="http://tempuri.org/IChatService/SendLobbyMessageResponse")]
        System.Threading.Tasks.Task<GameClient.ChatServiceReference.ChatOperationResult> SendLobbyMessageAsync(GameClient.ChatServiceReference.ChatMessageDto messageDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/SendPrivateMessage", ReplyAction="http://tempuri.org/IChatService/SendPrivateMessageResponse")]
        GameClient.ChatServiceReference.ChatOperationResult SendPrivateMessage(GameClient.ChatServiceReference.ChatMessageDto messageDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/SendPrivateMessage", ReplyAction="http://tempuri.org/IChatService/SendPrivateMessageResponse")]
        System.Threading.Tasks.Task<GameClient.ChatServiceReference.ChatOperationResult> SendPrivateMessageAsync(GameClient.ChatServiceReference.ChatMessageDto messageDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/LeaveLobbyChat", ReplyAction="http://tempuri.org/IChatService/LeaveLobbyChatResponse")]
        GameClient.ChatServiceReference.ChatOperationResult LeaveLobbyChat(GameClient.ChatServiceReference.JoinChatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/LeaveLobbyChat", ReplyAction="http://tempuri.org/IChatService/LeaveLobbyChatResponse")]
        System.Threading.Tasks.Task<GameClient.ChatServiceReference.ChatOperationResult> LeaveLobbyChatAsync(GameClient.ChatServiceReference.JoinChatRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/ReceiveMessage")]
        void ReceiveMessage(GameClient.ChatServiceReference.ChatMessageDto message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatServiceChannel : GameClient.ChatServiceReference.IChatService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChatServiceClient : System.ServiceModel.DuplexClientBase<GameClient.ChatServiceReference.IChatService>, GameClient.ChatServiceReference.IChatService {
        
        public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public GameClient.ChatServiceReference.ChatOperationResult JoinLobbyChat(GameClient.ChatServiceReference.JoinChatRequest request) {
            return base.Channel.JoinLobbyChat(request);
        }
        
        public System.Threading.Tasks.Task<GameClient.ChatServiceReference.ChatOperationResult> JoinLobbyChatAsync(GameClient.ChatServiceReference.JoinChatRequest request) {
            return base.Channel.JoinLobbyChatAsync(request);
        }
        
        public GameClient.ChatServiceReference.ChatOperationResult SendLobbyMessage(GameClient.ChatServiceReference.ChatMessageDto messageDto) {
            return base.Channel.SendLobbyMessage(messageDto);
        }
        
        public System.Threading.Tasks.Task<GameClient.ChatServiceReference.ChatOperationResult> SendLobbyMessageAsync(GameClient.ChatServiceReference.ChatMessageDto messageDto) {
            return base.Channel.SendLobbyMessageAsync(messageDto);
        }
        
        public GameClient.ChatServiceReference.ChatOperationResult SendPrivateMessage(GameClient.ChatServiceReference.ChatMessageDto messageDto) {
            return base.Channel.SendPrivateMessage(messageDto);
        }
        
        public System.Threading.Tasks.Task<GameClient.ChatServiceReference.ChatOperationResult> SendPrivateMessageAsync(GameClient.ChatServiceReference.ChatMessageDto messageDto) {
            return base.Channel.SendPrivateMessageAsync(messageDto);
        }
        
        public GameClient.ChatServiceReference.ChatOperationResult LeaveLobbyChat(GameClient.ChatServiceReference.JoinChatRequest request) {
            return base.Channel.LeaveLobbyChat(request);
        }
        
        public System.Threading.Tasks.Task<GameClient.ChatServiceReference.ChatOperationResult> LeaveLobbyChatAsync(GameClient.ChatServiceReference.JoinChatRequest request) {
            return base.Channel.LeaveLobbyChatAsync(request);
        }
    }
}
